### ISSUE TITLE
Midnight: a virtual pub

### ISSUE THREAD

**Issue by mikaa123** [maxboeck/whimsical#16]
__URL:__ https://midnight.pub
__Author's Twitter Handle:__ `@midnightpub_`

You find yourself in front of the midnight pub. As you push the door, you see the bartender preparing drinks for this weird looking person and his dog, and a room full of people. So, what will it be for you? Midnight is a pub, but virtual - a writing platform where you can connect and share your stories with others in an interconnected way.

**Comment by maxboeck** [comment]
this seems to be an interesting idea, but it requires sign up and is not what I'm looking for here. thanks!
