### ISSUE TITLE
Add this Website!

### ISSUE THREAD

**Issue by chrisaldrich** [maxboeck/whimsical#20]
__URL:__ https://www.kickscondor.com/
__Author's Twitter Handle: (optional)__ @kickscondor 

The fun feature I like most about this site is... the design aesthetic and the regular highlighting of quirky, fun, and off-the-beaten path content that it features. (It's also very likely a great source for other whimsical and interesting websites and creators). 

(Originally posted at https://boffosocko.com/2020/07/02/maxboeck-whimsical-github/)

**Comment by maxboeck** [comment]
Thanks, this looks very interesting. Going on the list!
