### ISSUE TITLE
Add this Website: Medieval cat meme generator

### ISSUE THREAD

**Issue by michael-klein** [maxboeck/whimsical#53]
__URL:__ https://michael-klein.github.io/medieval-cat-meme-generator/
__Author's Mastodon Handle: @michaelklein@vivaldi.net

I built this site quite a while ago when a certain twitter bot that posted silly cats in medieval pictures gave me a few good chuckles.
It's just a silly little thing to generate memes with funny old-timey cats in it.

**Comment by maxboeck** [comment]
thanks, added it to the club! 🎉
